-- text 2 base64 encoder generated by chatgpt on the 18th July 2026 at 5:09 PM CEST
-- not for production
local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

return function(data)
return ((data:gsub('.', function(x)
local byte = x:byte()
local bits = ''

for i = 8, 1, -1 do
    bits = bits .. (byte % 2 ^ i - byte % 2 ^ (i - 1) > 0 and '1' or '0')
    end

    return bits
    end) .. '0000'):gsub('%d%d%d?%d?%d?%d?', function(x)
    if #x < 6 then
        return ''
    end

    local c = 0
    for i = 1, 6 do
        if x:sub(i, i) == '1' then
            c = c + 2 ^ (6 - i)
            end
            end

            return b:sub(c + 1, c + 1)
            end) .. ({ '', '==', '=' })[#data % 3 + 1])
end
